### ISSUE TITLE
Data processing: pre API call

### ISSUE THREAD

**Issue by raprasad** [jj0hns0n/geonode#34] opened 2015-02-12 15:56 UTC
FIPS Example
- CSV file has FIPS county in 2 columns: 
     - state column (2 digits)
     - county column (3 digits)
- Pre-API call processing (@raprasad)
     - User specifies 2 columns as being the FIPS county
     - Additional column created for join purposes
- API call
     - csv upload:  file has newly combined FIPS column
     - join: specify new column for join

**Comment by blewis** [comment] 2015-02-18 19:23
Handled by #49

**Comment by jj0hns0n** [comment] 2015-02-18 20:56
Close as dupe of #49

**Closed by jj0hns0n** 2015-02-18 20:56 UTC
Labels: table-join
