### ISSUE TITLE
Data Cleaning: Joining on Census Tracts

### ISSUE THREAD

**Issue by raprasad** [jj0hns0n/geonode#30] opened 2015-02-11 19:50 UTC
### Data cleaning before API calls
- User specifies census tract column
- Convert census tract column data to 6 digits, left pad values with zeros
     - refererence:  https://www.census.gov/geo/reference/gtc/gtc_ct.html

### Cleaning steps for Census Tract Column (for each value):
1.  Strip value of decimals
2.  Is value is all digits and non-blank?   (No alphas, no empty strings, no other chars, etc)
    - No: Error row
3.  Zero-Pad value up to six digits.  ```val.zfill(6)```
4.  Make sure column itself is converted to a string column
    - csvkit?
    - pandas? (if on the dataverse side): http://stackoverflow.com/questions/23836277/add-leading-zeros-to-strings-in-pandas-dataframe

**Comment by raprasad** [comment] 2015-02-18 20:02
see #49

**Comment by jj0hns0n** [comment] 2015-02-18 20:57
Closing as dupe of #49

**Closed by jj0hns0n** 2015-02-18 20:57 UTC
Labels: table-join
